/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/episodes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Episodes */
    get: operations["list_episodes_api_episodes_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/episodes/{transcript_run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Episode Detail */
    get: operations["episode_detail_api_episodes__transcript_run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/episodes/{transcript_run_id}/analysis": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run Analysis */
    post: operations["run_analysis_api_episodes__transcript_run_id__analysis_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/episodes/{transcript_run_id}/questions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ask Question */
    post: operations["ask_question_api_episodes__transcript_run_id__questions_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnalysisRequest */
    AnalysisRequest: {
      /**
       * Consent
       * @constant
       */
      consent: true;
      /**
       * Refresh
       * @default false
       */
      refresh: boolean;
    };
    /** AnalysisResultView */
    AnalysisResultView: {
      analysis: components["schemas"]["EpisodeAnalysisView"];
      /** Analysis Run Id */
      analysis_run_id: number;
      /**
       * Cache Status
       * @enum {string}
       */
      cache_status: "cached" | "created";
      /** Created At */
      created_at: string;
      /** Model */
      model: string;
      /** Response Id */
      response_id: string;
      usage: components["schemas"]["UsageView"];
    };
    /** EpisodeAnalysisView */
    EpisodeAnalysisView: {
      /** Actionable Insights */
      actionable_insights: components["schemas"]["EvidenceBackedItemView"][];
      /** Claims */
      claims: components["schemas"]["EvidenceBackedItemView"][];
      /** Limitations */
      limitations: string[];
      /** People */
      people: components["schemas"]["EvidenceBackedItemView"][];
      summary: components["schemas"]["EvidenceBackedItemView"];
      /** Topics */
      topics: components["schemas"]["EvidenceBackedItemView"][];
    };
    /** EpisodeDetailResponse */
    EpisodeDetailResponse: {
      analysis: components["schemas"]["AnalysisResultView"] | null;
      episode: components["schemas"]["TranscriptMetadataView"];
      /** Max Question Chars */
      max_question_chars: number;
    };
    /** EpisodeListResponse */
    EpisodeListResponse: {
      /** Episodes */
      episodes: components["schemas"]["EpisodeSummaryView"][];
    };
    /** EpisodeSummaryView */
    EpisodeSummaryView: {
      /** Analysis Available */
      analysis_available: boolean;
      /** Episode Id */
      episode_id: number;
      /** Latest Analysis Status */
      latest_analysis_status: string | null;
      /** Latest Transcription Status */
      latest_transcription_status: string | null;
      /** Spotify Episode Id */
      spotify_episode_id: string | null;
      /** Title */
      title: string;
      /** Transcript Available */
      transcript_available: boolean;
      /** Transcript Run Id */
      transcript_run_id: number | null;
    };
    /** ErrorDetail */
    ErrorDetail: {
      /** Code */
      code: string;
      /** Message */
      message: string;
    };
    /** ErrorEnvelope */
    ErrorEnvelope: {
      error: components["schemas"]["ErrorDetail"];
    };
    /** EvidenceBackedItemView */
    EvidenceBackedItemView: {
      /** Evidence */
      evidence: components["schemas"]["EvidenceView"][];
      /** Text */
      text: string;
    };
    /** EvidenceView */
    EvidenceView: {
      /** Quote */
      quote: string;
      /** Segment Id */
      segment_id: string;
    };
    /** QuestionRequest */
    QuestionRequest: {
      /**
       * Consent
       * @constant
       */
      consent: true;
      /** Question */
      question: string;
    };
    /** QuestionResultView */
    QuestionResultView: {
      /** Answer */
      answer: string;
      /**
       * Cache Status
       * @default not_persisted
       * @constant
       */
      cache_status: "not_persisted";
      /** Evidence */
      evidence: components["schemas"]["EvidenceView"][];
      /** Insufficient Evidence */
      insufficient_evidence: boolean;
      /** Model */
      model: string;
      /** Response Id */
      response_id: string;
      /** Response Ids */
      response_ids: string[];
      /** Tool Calls */
      tool_calls: components["schemas"]["ToolTraceView"][];
      usage: components["schemas"]["UsageView"];
    };
    /** ToolTraceView */
    ToolTraceView: {
      /** Call Id */
      call_id: string;
      /** Response Id */
      response_id: string;
      /** Result Segment Ids */
      result_segment_ids: string[];
      /** Tool Name */
      tool_name: string;
    };
    /** TranscriptMetadataView */
    TranscriptMetadataView: {
      /** Created At */
      created_at: string;
      /** Episode Id */
      episode_id: number;
      /** Feed Url */
      feed_url: string;
      /** Rss Guid */
      rss_guid: string;
      /** Spotify Episode Id */
      spotify_episode_id: string | null;
      /** Title */
      title: string;
      /** Transcript Id */
      transcript_id: number;
      /** Transcript Run Id */
      transcript_run_id: number;
      /** Transcription Model */
      transcription_model: string;
    };
    /** UsageView */
    UsageView: {
      /** Input Tokens */
      input_tokens: number | null;
      /** Output Tokens */
      output_tokens: number | null;
      /** Total Tokens */
      total_tokens: number | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_episodes_api_episodes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeListResponse"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  episode_detail_api_episodes__transcript_run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transcript_run_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["EpisodeDetailResponse"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  run_analysis_api_episodes__transcript_run_id__analysis_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transcript_run_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AnalysisRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AnalysisResultView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
  ask_question_api_episodes__transcript_run_id__questions_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transcript_run_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["QuestionRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["QuestionResultView"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Internal Server Error */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Bad Gateway */
      502: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorEnvelope"];
        };
      };
    };
  };
}
